name: rpbp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - biopython
  - bowtie2
  - cmdstanpy>=1.0.0
  - dash
  - dash-bio
  - dash-bootstrap-components
  - fastqc
  - flexbar
  - joblib
  - numpy
  - pandas
  - pbiotools>=5.0.0
  - pyyaml
  - samtools
  - scipy
  - star
  - statsmodels
  - pysam
