name: rpbp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pbiotools>=5.0.0
  - appdirs
  - cmdstanpy>=1.0.0
  - dash
  - dash-bio
  - dash-bootstrap-components
  - pytest
  - pyyaml
  - statsmodels
  - bowtie2
  - fastqc
  - flexbar
  - samtools
  - star
